name: sirrujak-antimony # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lisp inspired CAD # 79 char long summary
description: |
  This is a community build of the Antimony 3D CAD tool based on a
  lisp philosophy. Software developed by Matt Keeter. https://github.com/mkeeter/antimony

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  antimony:
    command: bin/desktop-launch $SNAP/bin/antimony
    plugs: ['desktop', 'framebuffer', 'camera', 'network', 'home', 'opengl', 'x11', 'desktop-legacy']

parts:
  desktop-qt5:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
  antimony:
    #override-build: |
    #  #mv usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1.16 usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1
    #  #ls -s usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1.16 usr/lib/x86_64-linux-gnu/libpsm_infipath.so.1
    #  #snapcraftctl build
    # See 'snapcraft plugins'
    source: https://github.com/mkeeter/antimony.git
    source-type: git
    plugin: cmake
    configflags:
      - -GNinja
    after:
      - desktop-qt5
    stage:
      - -build/app/antimony
    stage-packages:
      - libpng-dev
      - python3-dev
      - qt5-default
      - libboost-all-dev
      - libpsm-infinipath1
    organize:
      usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1.16: usr/lib/x86_64-linux-gnu/libpsm_infinipath.so.1
    build-packages:
      - build-essential
      - libpng-dev
      - python3-dev
      - libboost-all-dev
      - libgl1-mesa-dev
      - lemon
      - flex
      - qt5-default
      - ninja-build
      - cmake
